##### Menu
menu:
  Home 首页: /
  Archives 归档: /archives
  Life Logs 日志: /lifelogs
  # Message board: /message board
  About 简介: /about
## you can create `tags` and `categories` folders in `../source`.
## And create a `index.md` file in each of them.
## set `front-matter`as
## layout: tags (or categories)
## title: tags (or categories)
## ---

#### Widgets
widgets:
- site
- category
- tag
# - tagcloud
# - recent_posts
- links
- rss
- donate
## provide seven widgets:category,tag,rss,archive,tagcloud,links,weibo


#### RSS 
rss: /atom.xml ## RSS address.

#### Image
imglogo:
  enable: true             ## display image logo true/false.
  src: http://7vzp68.com1.z0.glb.clouddn.com/common/logo.png	#img/logo.png        ## `.svg` and `.png` are recommended,please put image into the theme folder `/jacman/source/img`.
favicon: http://7vzp68.com1.z0.glb.clouddn.com/common/favicon.ico	#img/favicon.ico   ## size:32px*32px,`.ico` is recommended,please put image into the theme folder `/jacman/source/img`.     
apple_icon: http://7vzp68.com1.z0.glb.clouddn.com/common/jacman.jpg	#img/jacman.jpg ## size:114px*114px,please put image into the theme folder `/jacman/source/img`.
author_img: http://7vzp68.com1.z0.glb.clouddn.com/common/author.jpg	#img/author.jpg ## size:220px*220px.display author avatar picture.if don't want to display,please don't set this.

#### index post is expanding or not 
index:
  expand: false           ## default is unexpanding,so you can only see the short description of each post.
  excerpt_link: Read More
  
#### Author information
author:
  intro_line1:  "Less is more."		## your introduction on the bottom of the page
  intro_line2:  "寧靜致遠。"		## the 2nd line
  weibo:		icedes				## e.g. wuchong1014 or 2176287895 for http://weibo.com/2176287895
  weibo2:		2622530715			## e.g. wuchong1014 or 2176287895 for http://weibo.com/2176287895
  #weibo_verifier:					## e.g. b3593ceb Your weibo-show widget verifier ,if you use weibo-show it is needed.
  #tsina:							## e.g. 2176287895  Your weibo ID,It will be used in share button.
  douban:		IceHeGZ				## e.g. wuchong1014 or your id for https://www.douban.com/people/wuchong1014
  #zhihu:		he-zhi-yuan-15		## e.g. jark  for http://www.zhihu.com/people/jark
  email:		ice.he.hzy@gmail.com	## e.g. imjark@gmail.com
  #twitter:    	Ice_He_atPeking		## e.g. jarkwu for https://twitter.com/jarkwu
  github:		IceHe				## e.g. wuchong for https://github.com/wuchong
  #facebook:   	https://www.facebook.com/profile.php?id=100008252804677	## e.g. imjark for https://facebook.com/imjark
  #linkedin:   	http://cn.linkedin.com/pub/%E5%BF%97%E9%81%A0-%E4%BD%95/92/91/3ba	## e.g. wuchong1014 for https://www.linkedin.com/in/wuchong1014
  #google_plus:    					## e.g. "111190881341800841449" for https://plus.google.com/u/0/111190881341800841449, the "" is needed!
  #stackoverflow:  					## e.g. 3222790 for http://stackoverflow.com/users/3222790/jark
## if you set them, the corresponding  share button will show on the footer

#### Toc
toc:
  article: true		## show contents in article.
  aside: false		## show contents in aside.
## you can set both of the value to true of neither of them.
## if you don't want display contents in a specified post,you can modify `front-matter` and add `toc: false`.

#### Links
links:
  飘。Gone with the wind.: http://290841032.qzone.qq.com,飘。Gone with the wind.
  极地 · 雪: http://sf-zhou.github.io/,极地 · 雪
  Shiwey Yan: http://shiweyyan.github.io/,Shiwey Yan
  Jan Fan: http://janfan.github.io/,Jan Fan
  SF-_- 的 ACM 博客: http://blog.csdn.net/sf____,SF-_- 的 ACM 博客
#  码农圈: https://coderq.com,一个面向程序员交流分享的新一代社区
#  Jark's Blog: http://wuchong.me

  

#### Comment
duoshuo_shortname: icehe	## e.g. wuchong   your duoshuo short name.
disqus_shortname: icehe		## e.g. wuchong   your disqus short name.

#### Share button
jiathis:
  enable: false ## if you use jiathis as your share tool,the built-in share tool won't be display.
  id:    ## e.g. 1889330 your jiathis ID. 
  tsina: ## e.g. 2176287895 Your weibo id,It will be used in share button.
  
#### Analytics
google_analytics:
  enable: 	true
  id:  UA-60837823-1	## e.g. UA-46321946-2 your google analytics ID.
  site:  auto	## e.g. wuchong.me your google analytics site or set the value as auto.
google_analytics2:
  enable: 	true
  id:  UA-60837823-2	## e.g. UA-46321946-2 your google analytics ID.
  site:  auto	## e.g. wuchong.me your google analytics site or set the value as auto.
## You MUST upgrade to Universal Analytics first!
## https://developers.google.com/analytics/devguides/collection/upgrade/?hl=zh_CN
baidu_tongji:
  enable: true
  sitecode:  7076c1a5edd76a6bd49f8065ceecc7a4 ## e.g. e6d1f421bbc9962127a50488f9ed37d1 your baidu tongji site code
baidu_tongji2:
  enable: true
  sitecode:  68e951d2eed2725bdd8cf4b1900d632f ## e.g. e6d1f421bbc9962127a50488f9ed37d1 your baidu tongji site code
cnzz_tongji:
  enable: false
  siteid:    ## e.g. 1253575964 your cnzz tongji site id

#### Miscellaneous
ShowCustomFont: true  ## you can change custom font in `variable.styl` and `font.styl` which in the theme folder `/jacman/source/css`.
fancybox: true        ## if you use gallery post or want use fancybox please set the value to true.
totop: true           ## if you want to scroll to top in every post set the value to true


#### Custom Search
google_cse: 
  enable: false
  cx:   ## e.g. 018294693190868310296:abnhpuysycw your Custom Search ID.
## https://www.google.com/cse/ 
## To enable the custom search You must create a "search" folder in '/source' and a "index.md" file
## set the 'front-matter' as
## layout: search 
## title: search
## ---
baidu_search:     ## http://zn.baidu.com/
  enable: false
  id: "8026609685000529645"	## e.g. "783281470518440642"  for your baidu search id
  site: http://zhannei.baidu.com/cse/search  ## your can change to your site instead of the default site
baidu_search2:     ## http://zn.baidu.com/
  enable: false
  id: "915177976264389242"	## e.g. "783281470518440642"  for your baidu search id
  site: http://zhannei.baidu.com/cse/search  ## your can change to your site instead of the default site
tinysou:
  enable: true
  engineKeyGithub: "4b114b45fc7fe840f7cc"
  engineKeyGitcafe: "1f746b2042ed54f07a8d"
  
#### img图床 & att附件仓库
repo:
  img: http://7vzp68.com1.z0.glb.clouddn.com/
  att: http://7vzp67.com1.z0.glb.clouddn.com/

#原属性在icehe.blog.hexo下的_config.yml中，为了避免某bug，移到了这里。
#某bug详情：http://wuchong.me/blog/2015/03/12/support-jacman-to-Hexo-3/
highlight:
  enable: true
  line_number: true
  tab_replace: